`define LOAD_STORE_MEMORY_STAGE_ADDRESS 32

`define LOAD_STORE_MEMORY_STAGE_RD_DATA 32

`define LOAD_STORE_MEMORY_STAGE_RN_DATA 32

`define LOAD_STORE_MEMORY_STAGE_RD_ADDR 4

`define LOAD_STORE_MEMORY_STAGE_RN_ADDR 4

`define LOAD_STORE_MEMORY_STAGE_INSTR_TAG 4

`define LOAD_STORE_MEMORY_STAGE_W_EN 4

`define LOAD_STORE_MEMORY_STAGE_CTRL_LOAD_MUX 3

`define LOAD_STORE_MEMORY_STAGE_CTRL_STR_MUX 3

`define MEM_DATA_BUS_WIDTH 8

`define ADDR_BUS_WIDTH 32

`define DATA_MEM_SIZE 215

`define LOAD_STORE_MEMORY_STAGE_CONTROL_WORD 122

/******LOAD_STORE_MEMORY_STAGE_CONTROL_WORD******/
`define LOAD_STORE_MEMORY_STAGE_INSTR_TAG_START 121

`define LOAD_STORE_MEMORY_STAGE_INSTR_TAG_END 118

`define LOAD_STORE_MEMORY_STAGE_RD_ADDR_START 117

`define LOAD_STORE_MEMORY_STAGE_RD_ADDR_END 114

`define LOAD_STORE_MEMORY_STAGE_RN_ADDR_START 113

`define LOAD_STORE_MEMORY_STAGE_RN_ADDR_END 110

`define LOAD_STORE_MEMORY_STAGE_STORE_RD_DATA_START 109

`define LOAD_STORE_MEMORY_STAGE_STORE_RD_DATA_END 78

`define LOAD_STORE_MEMORY_STAGE_RN_DATA_START 77

`define LOAD_STORE_MEMORY_STAGE_RN_DATA_END 46

`define LOAD_STORE_MEMORY_STAGE_ADDRESS_START 45

`define LOAD_STORE_MEMORY_STAGE_ADDRESS_END 14

`define LOAD_STORE_MEMORY_STAGE_SWP_CTRL 13

`define LOAD_STORE_MEMORY_STAGE_CTRL_LOAD_MUX_START 12

`define LOAD_STORE_MEMORY_STAGE_CTRL_LOAD_MUX_END 10

`define LOAD_STORE_MEMORY_STAGE_CTRL_STR_MUX_START 9

`define LOAD_STORE_MEMORY_STAGE_CTRL_STR_MUX_END 7

`define LOAD_STORE_MEMORY_STAGE_WRITE_EN_START 6

`define LOAD_STORE_MEMORY_STAGE_WRITE_EN_END 3

`define LOAD_STORE_MEMORY_STAGE_INSTR_CONFIRMED 2

`define LOAD_STORE_MEMORY_STAGE_MULTIPLE_EN 1

`define LOAD_STORE_MEMORY_STAGE_START 0
/******LOAD_STORE_MEMORY_STAGE_CONTROL_WORD******/