`define LD_STR_ADDR_GEN_INSTR_TAG_SIZE 4

`define LD_STR_ADDR_GEN_RD_ADDR_SIZE 4

`define LD_STR_ADDR_GEN_RN_ADDR_SIZE 4

`define LD_STR_ADDR_GEN_COND_BITS_SIZE 4

`define LD_STR_ADDR_GEN_FLAG_REG_SIZE 4

`define LD_STR_ADDR_GEN_OPERANDB_SIZE 32

`define LD_STR_ADDR_GEN_SHIFT_FRM_RS_SIZE 5

`define LD_STR_ADDR_GEN_SHIFT_VALUE_SIZE 5

`define LD_STR_ADDR_GEN_SHIFT_OPCODE_SIZE 4

`define LD_STR_ADDR_GEN_BASE_ADDR_SIZE 32

`define LD_STR_ADDR_GEN_IMM_OFFSET_SIZE 12

`define LD_STR_ADDR_GEN_IMM_ADD_CALC_FUNC_SIZE 3

`define LD_STR_ADDR_GEN_IMM_W_EN_SIZE 4

`define LD_STR_ADDR_GEN_IMM_STR_RD_DATA_SIZE 32

`define LD_STR_ADDR_GEN_IMM_STR_RN_DATA_SIZE 32

`define LD_STR_ADDR_GEN_IMM_CTRL_LD_MUX_SIZE 3

`define LD_STR_ADDR_GEN_IMM_CTRL_STR_MUX_SIZE 3

`define LD_STR_RN_UPDATE_DATA_SIZE 32

`define LD_STR_ADDR_GEN_STAGE_LDM_STM_DATA_SIZE 16

`define LD_STR_ADDR_GEN_STAGE_FINAL_SHIFT_AMOUNT 5

`define LD_STR_ADDR_GEN_STAGE_OFFSET_FINAL 32

`define LD_STR_ADDR_GEN_STAGE_CONTROL_WORD 175

/******LD_STR_ADDR_GEN_STAGE_CONTROL_WORD******/
`define LD_STR_ADDR_GEN_STAGE_INSTR_TAG_START 174

`define LD_STR_ADDR_GEN_STAGE_INSTR_TAG_END 171

`define LD_STR_ADDR_GEN_STAGE_RD_ADDR_START 170

`define LD_STR_ADDR_GEN_STAGE_RD_ADDR_END 167

`define LD_STR_ADDR_GEN_STAGE_RN_ADDR_START 166

`define LD_STR_ADDR_GEN_STAGE_RN_ADDR_END 163

`define LD_STR_ADDR_GEN_STAGE_COND_BITS_START 162

`define LD_STR_ADDR_GEN_STAGE_COND_BITS_END 159

`define LD_STR_ADDR_GEN_STAGE_LDM_STM_DATA_START 158

`define LD_STR_ADDR_GEN_STAGE_LDM_STM_DATA_END 143

`define LD_STR_ADDR_GEN_STAGE_FLAG_REG_START 142

`define LD_STR_ADDR_GEN_STAGE_FLAG_REG_END 139

`define LD_STR_ADDR_GEN_STAGE_OPERANDB_START 138

`define LD_STR_ADDR_GEN_STAGE_OPERANDB_END 107

`define LD_STR_ADDR_GEN_STAGE_SHIFT_FRM_RS_START 106

`define LD_STR_ADDR_GEN_STAGE_SHIFT_FRM_RS_END 102

`define LD_STR_ADDR_GEN_STAGE_SHIFT_VALUE_START 101

`define LD_STR_ADDR_GEN_STAGE_SHIFT_VALUE_END 97

`define LD_STR_ADDR_GEN_STAGE_SHIFT_OPCODE_START 96

`define LD_STR_ADDR_GEN_STAGE_SHIFT_OPCODE_END 93

`define LD_STR_ADDR_GEN_STAGE_USE_RS_TO_SHIFT 92

`define LD_STR_ADDR_GEN_STAGE_BASE_ADDR_START 91

`define LD_STR_ADDR_GEN_STAGE_BASE_ADDR_END 60

`define LD_STR_ADDR_GEN_STAGE_CTRL_REG_IMM_FOR_OFFSET 59

`define LD_STR_ADDR_GEN_STAGE_IMM_OFFSET_START 58

`define LD_STR_ADDR_GEN_STAGE_IMM_OFFSET_END 47

`define LD_STR_ADDR_GEN_STAGE_ADD_CALC_FUNC_START 46

`define LD_STR_ADDR_GEN_STAGE_ADD_CALC_FUNC_END 44

`define LD_STR_ADDR_GEN_STAGE_W_EN_START 43

`define LD_STR_ADDR_GEN_STAGE_W_EN_END 40

`define LD_STR_ADDR_GEN_STAGE_STR_RD_DATA_START 39 

`define LD_STR_ADDR_GEN_STAGE_STR_RD_DATA_END 8

`define LD_STR_ADDR_GEN_STAGE_CTRL_LD_MUX_START 7 

`define LD_STR_ADDR_GEN_STAGE_CTRL_LD_MUX_END 5

`define LD_STR_ADDR_GEN_STAGE_CTRL_STR_MUX_START 4

`define LD_STR_ADDR_GEN_STAGE_CTRL_STR_MUX_END 2

`define LD_STR_ADDR_GEN_STAGE_LD_STR_MULTIPLE 1

`define LD_STR_ADDR_GEN_STAGE_PIPE_START 0
/******LD_STR_ADDR_GEN_STAGE_CONTROL_WORD******/