`define TAG_BITS_SIZE 4

`define REORDER_BUFFER_SIZE 16

/******TAG_BITS_COMBINED******/
`define TAG_BITS_ALL_PIPES_COMBINED 16

`define TAG_BITS_ALU_PIPE1_STARTS 15

`define TAG_BITS_ALU_PIPE1_ENDS 12

`define TAG_BITS_ALU_PIPE2_STARTS 11

`define TAG_BITS_ALU_PIPE2_ENDS 8

`define TAG_BITS_LOAD_STORE_PIPE3_STARTS 7

`define TAG_BITS_LOAD_STORE_PIPE3_ENDS 4

`define TAG_BITS_BRANCH_PIPE4_STARTS 3

`define TAG_BITS_BRANCH_PIPE4_ENDS 0
/******TAG_BITS_COMBINED******/

`define TAG_RD_ISSUE 4

`define RD_ADDR_ISSUE 4

`define TAG_RN_ISSUE 12

/******TAG_RN_ISSUE******/
`define TAG_RN_ISSUE_ALU_PIPE1_STARTS 11

`define TAG_RN_ISSUE_ALU_PIPE1_ENDS 8

`define TAG_RN_ISSUE_ALU_PIPE2_STARTS 7

`define TAG_RN_ISSUE_ALU_PIPE2_ENDS 4

`define TAG_RN_ISSUE_LOAD_STORE_PIPE3_STARTS 3

`define TAG_RN_ISSUE_LOAD_STORE_PIPE3_ENDS 0
/******TAG_RN_ISSUE******/

`define TAG_RM_ISSUE 16

/******TAG_RM_ISSUE******/
`define TAG_RM_ISSUE_ALU_PIPE1_STARTS 15

`define TAG_RM_ISSUE_ALU_PIPE1_ENDS 12

`define TAG_RM_ISSUE_ALU_PIPE2_STARTS 11

`define TAG_RM_ISSUE_ALU_PIPE2_ENDS 8

`define TAG_RM_ISSUE_LOAD_STORE_PIPE3_STARTS 7

`define TAG_RM_ISSUE_LOAD_STORE_PIPE3_ENDS 4

`define TAG_RM_ISSUE_BRANCH_PIPE4_STARTS 3

`define TAG_RM_ISSUE_BRANCH_PIPE4_ENDS 0
/******TAG_RM_ISSUE******/

/******TAG_RS_ISSUE******/
`define TAG_RS_ISSUE 12

`define TAG_RS_ISSUE_ALU_PIPE1_STARTS 11

`define TAG_RS_ISSUE_ALU_PIPE1_ENDS 8

`define TAG_RS_ISSUE_ALU_PIPE2_STARTS 7

`define TAG_RS_ISSUE_ALU_PIPE2_ENDS 4

`define TAG_RS_ISSUE_LOAD_STORE_PIPE3_STARTS 3

`define TAG_RS_ISSUE_LOAD_STORE_PIPE3_ENDS 0
/******TAG_RS_ISSUE******/

/******REG_ADDR_COMBINED******/
`define REG_ADDR_PIPES_COMBINED 16

`define REG_ADDR_ALU_PIPE1_STARTS 15

`define REG_ADDR_ALU_PIPE1_ENDS 12

`define REG_ADDR_ALU_PIPE2_STARTS 11

`define REG_ADDR_ALU_PIPE2_ENDS 8

`define REG_ADDR_LOAD_STORE_PIPE3_STARTS 7

`define REG_ADDR_LOAD_STORE_PIPE3_ENDS 4

`define REG_ADDR_BRANCH_PIPE4_STARTS 3

`define REG_ADDR_BRANCH_PIPE4_ENDS 0
/******REG_ADDR_COMBINED******/

`define RD_DATA_PIPES 32

`define RN_DATA_PIPES 96

/******RN_DATA_PIPES******/
`define RN_DATA_ALU_PIPE1_STARTS 95

`define RN_DATA_ALU_PIPE1_ENDS 64

`define RN_DATA_ALU_PIPE2_STARTS 63

`define RN_DATA_ALU_PIPE2_ENDS 32

`define RN_DATA_LOAD_STORE_PIPE3_STARTS 31

`define RN_DATA_LOAD_STORE_PIPE3_ENDS 0
/******RN_DATA_PIPES******/

`define RM_DATA_PIPES 128

/******RM_DATA_PIPES******/
`define RM_DATA_ALU_PIPE1_STARTS 127

`define RM_DATA_ALU_PIPE1_ENDS 96

`define RM_DATA_ALU_PIPE2_STARTS 95

`define RM_DATA_ALU_PIPE2_ENDS 64

`define RM_DATA_LOAD_STORE_PIPE3_STARTS 63

`define RM_DATA_LOAD_STORE_PIPE3_ENDS 32

`define RM_DATA_BRANCH_PIPE4_STARTS 31

`define RM_DATA_BRANCH_PIPE4_ENDS 0
/******RM_DATA_PIPES******/

`define RS_DATA_PIPES 96

/******RS_DATA_PIPES******/
`define RS_DATA_ALU_PIPE1_STARTS 95

`define RS_DATA_ALU_PIPE1_ENDS 64

`define RS_DATA_ALU_PIPE2_STARTS 63

`define RS_DATA_ALU_PIPE2_ENDS 32

`define RS_DATA_LOAD_STORE_PIPE3_STARTS 31

`define RS_DATA_LOAD_STORE_PIPE3_ENDS 0
/******RS_DATA_PIPES******/

/******RN_ADDR_ISSUE******/
`define RN_ADDR_ISSUE 12

`define RN_ADDR_ISSUE_ALU_PIPE1_STARTS 11

`define RN_ADDR_ISSUE_ALU_PIPE1_ENDS 8

`define RN_ADDR_ISSUE_ALU_PIPE2_STARTS 7

`define RN_ADDR_ISSUE_ALU_PIPE2_ENDS 4

`define RN_ADDR_ISSUE_LOAD_STORE_PIPE3_STARTS 3

`define RN_ADDR_ISSUE_LOAD_STORE_PIPE3_ENDS 0
/******RN_ADDR_ISSUE******/

/******RM_ADDR_ISSUE******/
`define RM_ADDR_ISSUE 16

`define RM_ADDR_ISSUE_ALU_PIPE1_STARTS 15

`define RM_ADDR_ISSUE_ALU_PIPE1_ENDS 12

`define RM_ADDR_ISSUE_ALU_PIPE2_STARTS 11

`define RM_ADDR_ISSUE_ALU_PIPE2_ENDS 8

`define RM_ADDR_ISSUE_LOAD_STORE_PIPE3_STARTS 7

`define RM_ADDR_ISSUE_LOAD_STORE_PIPE3_ENDS 4

`define RM_ADDR_ISSUE_BRANCH_PIPE4_STARTS 3

`define RM_ADDR_ISSUE_BRANCH_PIPE4_ENDS 0
/******RM_ADDR_ISSUE******/

/******RS_ADDR_ISSUE******/
`define RS_ADDR_ISSUE 12

`define RS_ADDR_ISSUE_ALU_PIPE1_STARTS 11

`define RS_ADDR_ISSUE_ALU_PIPE1_ENDS 8

`define RS_ADDR_ISSUE_ALU_PIPE2_STARTS 7

`define RS_ADDR_ISSUE_ALU_PIPE2_ENDS 4

`define RS_ADDR_ISSUE_LOAD_STORE_PIPE3_STARTS 3

`define RS_ADDR_ISSUE_LOAD_STORE_PIPE3_ENDS 0
/******RS_ADDR_ISSUE******/

/******TAG_CPSR_ISSUE******/
`define TAG_CPSR_ISSUE 16

`define TAG_CPSR_ISSUE_ALU_PIPE1_STARTS 15

`define TAG_CPSR_ISSUE_ALU_PIPE1_ENDS 12

`define TAG_CPSR_ISSUE_ALU_PIPE2_STARTS 11

`define TAG_CPSR_ISSUE_ALU_PIPE2_ENDS 8

`define TAG_CPSR_ISSUE_LOAD_STORE_PIPE3_STARTS 7

`define TAG_CPSR_ISSUE_LOAD_STORE_PIPE3_ENDS 4

`define TAG_CPSR_ISSUE_BRANCH_PIPE4_STARTS 3

`define TAG_CPSR_ISSUE_BRANCH_PIPE4_ENDS 0
/******TAG_CPSR_ISSUE******/

`define CPSR_DATA_PIPES 128

/******CPSR_DATA_PIPES******/
`define CPSR_DATA_ALU_PIPE1_STARTS 127

`define CPSR_DATA_ALU_PIPE1_ENDS 96

`define CPSR_DATA_ALU_PIPE2_STARTS 95

`define CPSR_DATA_ALU_PIPE2_ENDS 64

`define CPSR_DATA_LOAD_STORE_PIPE3_STARTS 63

`define CPSR_DATA_LOAD_STORE_PIPE3_ENDS 32

`define CPSR_DATA_BRANCH_PIPE4_STARTS 31

`define CPSR_DATA_BRANCH_PIPE4_ENDS 0
/******CPSR_DATA_PIPES******/

`define LDM_STM_REG_SIZE 16

`define LDM_STM_DATA_SIZE 37

/******LOAD_STORE_MULTIPLE_DATA******/
`define LDM_STM_DATA_ENABLE 36

`define LDM_STM_DATA_RD_ADDR_STARTS 35

`define LDM_STM_DATA_RD_ADDR_ENDS 32

`define LDM_STM_DATA_RD_DATA_STARTS 31

`define LDM_STM_DATA_RD_DATA_ENDS 0
/******LOAD_STORE_MULTIPLE_DATA******/

/******REORDER_CONTROL_WORD******/
`define RB_NEW_ENTRY_WORD_SIZE 21

`define RB_TAG_START 20

`define RB_TAG_END 17

`define RB_RD_ADDR_START 16

`define RB_RD_ADDR_END 13

`define RB_RN_ADDR_START 12

`define RB_RN_ADDR_END 9

`define RB_CPSR_SPECULATIVE_INSTR 8

`define RB_CPSR_OVERFLOW_CONTROL 7

`define RB_RD_UPDATE 6

`define RB_RN_UPDATE 5

`define RB_CPSR_UPDATE 4

`define RB_ALU_TYPE_INSTR 3

`define RB_LOAD_STORE_TYPE_INSTR 2

`define RB_LOAD_STORE_MULTIPLE_TYPE_INSTR 1

`define RB_BRANCH_TYPE_INSTR 0
/******REORDER_CONTROL_WORD******/

`define DATA_RETIRE 128

/******INSTRUCTION_RETIRE_DATA******/
`define DATA_RETIRE_PORT1_STARTS 127

`define DATA_RETIRE_PORT1_ENDS 96

`define DATA_RETIRE_PORT2_STARTS 95

`define DATA_RETIRE_PORT2_ENDS 64

`define DATA_RETIRE_PORT3_STARTS 63

`define DATA_RETIRE_PORT3_ENDS 32

`define DATA_RETIRE_PORT4_STARTS 31

`define DATA_RETIRE_PORT4_ENDS 0
/******INSTRUCTION_RETIRE_DATA******/

`define RETIRE_WRITE_PORTS 4

/******INSTRUCTION_RETIRE_WRITE_EN******/
`define RETIRE_EN_PORT1 3

`define RETIRE_EN_PORT2 2

`define RETIRE_EN_PORT3 1

`define RETIRE_EN_PORT4 0
/******INSTRUCTION_RETIRE_WRITE_EN******/